export enum UserResponseStatus {
    USER_CREATED = "USER_CREATED",
    PASSWORDS_NOT_EQUAL = "PASSWORDS_NOT_EQUAL",
    USER_ALREADY_EXIST = "USER_ALREADY_EXIST",
    USER_GET = "USER_GET",
    USER_LIST = "USER_LIST",
    USER_DELETED = "USER_DELETED",
    USER_UPDATED = "USER_UPDATED"
}
